language: go

go:
  - "1.16"

services:
  - docker

env:
  global:
    - GOLANG_VERSION="${TRAVIS_GO_VERSION}"
    - APP_VERSION="${TRAVIS_TAG:-development}"
    - VIPS_VERSION=8.10.0

cache:
  apt: true
  directories:
    - $HOME/vips

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - go get github.com/mattn/goveralls

script:
  - make test_in_docker
  - make GOLANG_VERSION="${GOLANG_VERSION%.x}" VIPS_VERSION="${VIPS_VERSION}" APP_VERSION="${APP_VERSION}" DOCKER_IMAGE="${DOCKER_IMAGE}" image

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out

notifications:
  email: true