dist: trusty
sudo: false

language: node_js

node_js:
  - 14

services:
  - mongodb

jobs:
  fast_finish: true
  include:
    - stage: install
      script:
        - npm install
    - stage: check
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test:coveralls
    - stage: deploy
      script:
        - npm run prepublish
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t "$DOCKER_USERNAME/$DOCKER_IMAGEE:$TRAVIS_COMMIT" -f .travis-dockerfile .
        - docker push "$DOCKER_USERNAME/$DOCKER_IMAGE:$TRAVIS_COMMIT"

stages:
  - install
  - check
  - test
  - deploy

cache: npm
notifications:
  email: true