language: go

go:
  - "1.16"

services:
  - docker

env:
  global:
    - GOLANG_VERSION="${TRAVIS_GO_VERSION}"
    - MIM_VERSION="${TRAVIS_TAG:-development}"
  matrix:
    - LIBVIPS=8.10.0

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull abdollahpour/micro-image-manager:latest || true

script:
  - docker build --pull --cache-from abdollahpour/micro-image-manager:latest --build-arg GOLANG_VERSION="${GOLANG_VERSION%.x}" --build-arg LIBVIPS_VERSION="${LIBVIPS}" --build-arg MIM_VERSION="${MIM_VERSION}" --tag abdollahpour/micro-image-manager:${MIM_VERSION} --tag abdollahpour/micro-image-manager:latest -f docker/Dockerfile .
  - docker push abdollahpour/micro-image-manager:${MIM_VERSION}
  - docker push abdollahpour/micro-image-manager:latest

notifications:
  email: true