FROM abdollahpour/go-libvip:1.17
ARG APP_VERSION=edge

WORKDIR ${GOPATH}/src/github.com/abdollahpour/micro-image-manager

COPY go.mod .
COPY go.sum .
COPY Makefile .

RUN go get github.com/mattn/goveralls

COPY internal internal/
COPY cmd cmd/

RUN make get test