FROM abdollahpour/go-libvip:1.17
ARG APP_VERSION=edge

WORKDIR ${GOPATH}/src/github.com/abdollahpour/micro-image-manager

RUN apt-get install -y zip

COPY go.mod .
COPY go.sum .
COPY Makefile .

RUN make get

COPY internal internal/
COPY cmd cmd/

CMD make compile_in_docker archive_in_docker
