ARG GOLANG_VERSION=1.16
FROM golang:${GOLANG_VERSION} as builder
ARG APP_VERSION=edge
ARG VIPS_VERSION=8.10.0

# Installs libvips + required libraries
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update && \
  apt-get install --no-install-recommends -y \
  ca-certificates \
  automake build-essential curl \
  gobject-introspection gtk-doc-tools libglib2.0-dev libjpeg62-turbo-dev libpng-dev \
  libwebp-dev libtiff5-dev libgif-dev libexif-dev libxml2-dev libpoppler-glib-dev \
  swig libmagickwand-dev libpango1.0-dev libmatio-dev libopenslide-dev libcfitsio-dev \
  libgsf-1-dev fftw3-dev liborc-0.4-dev librsvg2-dev libimagequant-dev libheif-dev && \
  cd /tmp && \
  curl -fsSLO https://github.com/libvips/libvips/releases/download/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz && \
  tar zvxf vips-${VIPS_VERSION}.tar.gz && \
  cd /tmp/vips-${VIPS_VERSION} && \
  CFLAGS="-g -O3" CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 -g -O3" \
  ./configure \
  --disable-debug \
  --disable-dependency-tracking \
  --disable-introspection \
  --disable-static \
  --enable-gtk-doc-html=no \
  --enable-gtk-doc=no \
  --enable-pyvips8=no && \
  make && \
  make install && \
  ldconfig

WORKDIR ${GOPATH}/src/github.com/abdollahpour/micro-image-manager

COPY go.mod .
COPY go.sum .
COPY Makefile .

RUN go get github.com/mattn/goveralls

COPY internal internal/
COPY cmd cmd/

RUN make get test