apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: micro-image-manager-build
spec:
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: builtImage
        type: image
  workspaces:
    - name: source
    - name: cache
  params:
    - name: imageTag
      description: Tag of the images to be used.
  steps:
    - name: build
      image: golang:1.16
      workingDir: $(workspaces.source.path)
      script: |
        make dependencies
        make build
    - name: push
      image: gcr.io/kaniko-project/executor:v1.6.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/docker/Dockerfile-tkn
        - --destination=$(resources.outputs.builtImage.url):$(params.imageTag)
        - --context=$(workspaces.source.path)
