apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: micro-image-manager-deploy
spec:
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: builtImage
        type: image
  workspaces:
    - name: source
  params:
    - name: imageTag
      description: Tag of the images to be used.
    - name: namespace
      description: Target namespace
  steps:
    - name: deploy
      image: lachlanevenson/k8s-helm:v3.6.2
      workingDir: $(workspaces.source.path)
      script: |
        helm upgrade \
          -f chart/values/production.yml \
          --install \
          --set "image.repository=$(resources.outputs.builtImage.url)" \
          --set "image.tag=$(params.imageTag)" \
          --set "image.pullPolicy=Always" \
          --timeout "4m0s" \
          --wait \
          --namespace "$(params.namespace)" \
          micro-image-manager /workspace/source/chart
