apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: micro-image-manager-deploy
spec:
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: builtImage
        type: image
  workspaces:
    - name: source
  params:
    - name: imageTag
      description: Tag of the images to be used.
    - name: namespace
      description: Target namespace
    - name: host
      description: Host for deployment
    - name: secret
      description: generated certificate name
  steps:
    - name: deploy
      image: lachlanevenson/k8s-helm:v3.6.2
      workingDir: $(workspaces.source.path)
      script: |
        helm upgrade -f - \
          --install \
          --timeout "4m0s" \
          --wait \
          --namespace "$(params.namespace)" \
          --debug \
          micro-image-manager /workspace/source/chart << EOF
          image:
            repository: $(resources.outputs.builtImage.url)
            tag: $(params.imageTag)
            pullPolicy: Always
          ingress:
            annotations:
              kubernetes.io/ingress.class: "nginx"
              kubernetes.io/tls-acme: "true"
            hosts:
              - host: $(params.host)
                publicManagement: true
            tls:
              - secretName: $(params.secret)
                hosts:
                  - $(params.host)
        EOF
