apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: micro-image-manager-test
spec:
  resources:
    inputs:
      - name: source
        type: git
  workspaces:
    - name: source
  steps:
    - name: image
      image: gcr.io/kaniko-project/executor:v1.6.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/docker/Dockerfile-test
        - --context=$(workspaces.source.path)
        - --no-push
